"""replace_age_with_birth_date

Revision ID: f93c63e8a162
Revises: 694d0e927254
Create Date: 2026-07-03 08:57:13.027423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93c63e8a162'
down_revision: Union[str, Sequence[str], None] = '694d0e927254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('birth_date', sa.Date(), nullable=False))
    op.drop_column('employees', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('age', sa.INTEGER(), nullable=False))
    op.drop_column('employees', 'birth_date')
    # ### end Alembic commands ###
